### 1. Control flow within a function

A [leap year](https://en.wikipedia.org/wiki/Leap_year) contains one additional day and occurs every 4 years. Years that are evenly divisble by 100 are not leap years, except years that are evely divisible by 400 (which are leap years).

Write a function `leap_year(n)`, that takes an integer `n` which represents the year, and returns `True` if `n` is a leap year and `False` if not. Test your function with the following years: `1600, 2020, 5, 2015, 2100`

In [ ]:
def leap_year(n):
    ...

### 2. Calling a function within a loop

Assume you have the three lists `cargo`, `actual` and `nominal` as defined in the cell below. 

First, write a function `commission` with three arguments `cargo`, `actual` and `nominal` that prints the cargo, determines the difference between actual and nominal values and then prints and returns the result.

Now write a `for`-loop, that iterates over the three lists and calls the function in each iteration.

Lastly, include a keyword-argument `warn` with the default `False`, that prints a short warning, only if the difference between actual and nominal is greater than 25, and if `warn` is `True`. Then, rerun the loop, with `warn=True`.

In [ ]:
cargo = ['bananas', 'apples', 'milk']
actual = [24, 24, 12]
nominal = [4, 52, 0]



### 3. Good practises
Have a look at the following code:
```python
a='melons'; b=0; c=1
def f(x):
    x=x + 10
    return x
from numpy import *
d=sqrt(f(b))
print(d>1)
```
It defines an actual value of `1` melon, and defines the nominal value as `0`. Then a function is defined that adds `10` to, in this case, the actual value. The `numpy` function `sqrt()` is called after importing it, to calculate the square root of the actual value. Finally, the result is compared to the nominal value.

Try to understand the code and modify it to make it more readable and reusable: Replace all variable and function names with meaningful ones and comment the code. Afterwards, compare your new code with the old version above and convince yourself how much more readable the new version is

### 4. Functional array creation and manipulation

Make use of `numpy.array` to create an array `a` and stepwise produce the output listed below. Try not to create `a` explicitely, but try to use `numpy`-functions:
1. `print(a)` yields the following output:
```
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 2. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
```
2. Manipulate `a` such that `print(a)` yields the following output:
```
[[0. 0. 0. 0. 0.]
 [0. 3. 3. 3. 0.]
 [0. 3. 6. 3. 0.]
 [0. 3. 3. 3. 0.]
 [0. 0. 0. 0. 0.]]
```
3. Manipulate `a` further such that `print(a)` yields the following output:
```
[[0. 0. 0. 0. 0.]
 [0. 4. 3. 3. 0.]
 [0. 3. 8. 3. 0.]
 [0. 3. 3. 6. 0.]
 [0. 0. 0. 0. 4.]]
```
4. Manipulate `a` further such that `print(a)` yields the following output:
```
[[ 0.  0.  0.  0.  0.]
 [ 0.  4. -3. -3.  0.]
 [ 0.  3. -8. -3.  0.]
 [ 0.  3.  3.  6.  0.]
 [ 0.  0.  0.  0.  4.]]
```
5. Manipulate `a` further such that `print(a)` yields the following output:
```
[[ 0.  0.  0.  0.  0.]
 [ 0.  4.  3.  3.  0.]
 [ 0. -3. -8.  3.  0.]
 [ 0. -3. -3.  6.  0.]
 [ 0.  0.  0.  0.  4.]]
```

In [ ]:
import numpy as np



### 5. Converting and plotting coordinates with `sunpy`

Take a look at the script below, that transforms coordinates from the Sun's surface into pixel coordinates and then plots them (see `sunpy_instructor.ipynb`). 

Modify the script to also show coordinate values along the equator.

In [ ]:
import matplotlib.pyplot as plt
import sunpy.map
import astropy.units as u
from astropy.coordinates import SkyCoord
from sunpy.coordinates import frames

downloaded_files = ['data/hmi.m_720s.20220101_000000_TAI.3.magnetogram.fits', ]
hmi_map = sunpy.map.Map(downloaded_files[0])
# hmi_map = hmi_map.rotate(order=3)

fig = plt.figure(2, figsize=(15, 8))
ax = hmi_map.plot()
limb = hmi_map.draw_limb()
grid = hmi_map.draw_grid()
clb = plt.colorbar()

coordinates_text = (r'$0^\circ$', r'$15^\circ$', 
                    r'$30^\circ$', r'$45^\circ$')
xy_coordinates = ((0, 0), (0, 15), (0, 30), (0, 45))

for i, coord in enumerate(coordinates_text):
    x, y = xy_coordinates[i]
    xy_StonyHurst = SkyCoord(x*u.deg, y*u.deg, 
                             frame=frames.HeliographicStonyhurst)
    xy_HelioProjective = xy_StonyHurst.transform_to(hmi_map.coordinate_frame)
    xy_PixelCoordinates = hmi_map.world_to_pixel(xy_HelioProjective)
    
    ax.axes.text(xy_PixelCoordinates.x.value + 5, 
                 xy_PixelCoordinates.y.value + 10, 
                 coordinates_text[i], color='white', 
                 fontsize=12)